### PR TITLE
Edit does not render

### LINKED ISSUE #76: [Web Components] Input/Edit does not render
There's an error: 
> Uncaught ReferenceError: Fragment is not defined

Maybe we would have to use a wrapper element like `div` instead of a Fragment so that the React component can be converted correctly

### PR DESCRIPTION
**Pull request by zarkoboyadjiev-zz**
Closes #76

### CODE REVIEW

File: packages/components/react-web/src/Icon/icons/IconEdit.jsx [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
+
+/** @jsxRuntime classic */
+/** @jsx jsx */
+import { jsx } from "@emotion/core";
+import PropTypes from "prop-types";
+import iconStyles from "../Icon.styles";
+
+function IconCamera(props) {
+  return (
```
Comment (kidroca) [inline packages/components/react-web/src/Icon/icons/IconEdit.jsx]: This file needs to be generated
I don't see changes that would (re)generate this file

See how `buildIconComponents.mjs` 
it uses `const iconSources = elements.icons;` to generate React components
1. the `edit` icon needs to be added to `packages/elements/src/icons/svg`
2. then `packages/elements/src/icons/index` should be rebuilt (buildIndexJs.mjs)
3. then `react-web` Icons rebuilt - `buildIconComponents.mjs` 
4. Finally everything committed

**Review by kidroca — CHANGES_REQUESTED** [review]

File: packages/components/react-web/src/Icon/icons/IconEdit.jsx (hunk 1 above)
Comment (kendrick) [reply packages/components/react-web/src/Icon/icons/IconEdit.jsx]: Sorry for any confusion and for the lack of documentation around this! I’ll add a readme in this folder that explains the process.

**Review by kidroca — APPROVED** [review]
Looks good thanks
